version: '3'
services:
  aws-rds-db:
    image: hyongkui/bus_api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - USER=${RDS_USER}
      - DB_HOST=${RDS_DB_HOST}
      - USER_PWD=${RDS_PWD}
